'''
Created on Jul 18, 2013

@author: richilb
'''

import csv

class Category(object):
    
    '''
    Get the data from bug_alias_owners.csv which was generated by the script and build a dictionary out of it:
    For the dictionary: {key: 'SPOC'; Value: 'Category, alias, SPOC'} 
    '''
    def __init__(self):
        self.catdict = {}
        try:
            spamReader = csv.reader(open('/homes/richilb/workspace/DAM/src/bin/bug_alias_owners.csv'), delimiter=' ', quotechar='|')
            for row in spamReader:
                # print row[0].split(",")[2]
                column = row[0].split(",")
                # print column[0], ' | ', column[1], ' | ', column[2]
                # print ', '.join(row)
                self.catdict.setdefault(column[2], []).append(row[0])
        except Exception, e:
            self.catdict = None
            print e.message
        
    # Generate a list of all aliases for a particular user        
    def listAliasForUser(self, username):
        if self.catdict.get(username) != None:
            aliasList =  [value.split(',')[1] for value in self.catdict.get(username)]
            return list(set(aliasList))
        else:
            return None
    
    # Generate a list of all Categoriess for a particular user
    def listCategoriesForUser(self, username):
        if self.catdict.get(username) != None:
            catList = [value.split(',')[0] for value in self.catdict.get(username)]
            return list(set(catList))
        else:
            return None
    
    # Generate a list of all categories in the JUNOS system
    def listAllCategories(self):
        catList = []
        for key, value in self.catdict.items():
            for v in value:
                catList.append(v.split(',')[0])
            
        return list(set(catList))
